# plugins:
#   - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
# include:
#   - CONTRIBUTING.md
#   - README.md
#   - LICENSE.md
#   - COPYING.md
#   - CODE_OF_CONDUCT.md
#   - CONTRIBUTING.md
#   - ISSUE_TEMPLATE.md
#   - PULL_REQUEST_TEMPLATE.md

markdown: GFM
# markdown: kramdown
# kramdown:
#   # input: Kramdown
#   input: GFM
#   math_engine: mathjax
#   syntax_highlighter: rouge
#   syntax_highlighter: coderay  